import { createTheme } from '@vanilla-extract/css';
import { defineProperties, createSprinkles } from '@vanilla-extract/sprinkles';

export const [themeClass, vars] = createTheme({
  color: {
    black: `#000`,
    nearBlack: `#111`,
    darkGray: `#333`,
    midGray: `#555`,
    gray: `#777`,
    silver: `#999`,
    lightSilver: `#aaa`,
    moonGray: `#ccc`,
    lightGray: `#eee`,
    nearWhite: `#f4f4f4`,
    white: `#fff`,
    darkRed: `#e7040f`,
    red: `#ff4136`,
    lightRed: `#ff725c`,
    orange: `#ff6300`,
    gold: `#ffb700`,
    yellow: `#ffd700`,
    lightYellow: `#fbf1a9`,
    purple: `#5e2ca5`,
    lightPurple: `#a463f2`,
    darkPink: `#d5008f`,
    hotPink: `#ff41b4`,
    pink: `#ff80cc`,
    lightPink: `#ffa3d7`,
    darkGreen: `#137752`,
    green: `#19a974`,
    lightGreen: `#9eebcf`,
    navy: `#001b44`,
    darkBlue: `#00449e`,
    blue: `#357edd`,
    lightBlue: `#96ccff`,
    lightestBlue: `#cdecff`,
    washedBlue: `#f6fffe`,
    washedGreen: `#e8fdf5`,
    washedYellow: `#fffceb`,
    washedRed: `#ffdfdf`,
    highlight: `#ffff00`,
  },
  fontSize: {
    p: `1rem`,
    h1: `3.052rem`,
    h2: `2.441rem`,
    h3: `1.953rem`,
    h4: `1.563rem`,
    h5: `1.25rem`,
    h6: `1rem`,
    small: `0.8rem`,
    disclaimer: `0.64rem`,
  },
  fontWeight: {
    '100': `100`,
    '200': `200`,
    '300': `300`,
    '400': `400`,
    '500': `500`,
    '600': `600`,
    '700': `700`,
    '800': `800`,
    '900': `900`,
  },
  space: {
    '0': `0`,
    '1': `1px`,
    '2': `2px`,
    '4': `4px`,
    '8': `8px`,
    '12': `12px`,
    '16': `16px`,
    '20': `20px`,
    '24': `24px`,
    '28': `28px`,
    '32': `32px`,
    '48': `48px`,
    '64': `64px`,
    '80': `80px`,
    '96': `96px`,
    '128': `128px`,
    '100': `100%`,
  },
});

const styles = defineProperties({
  conditions: {
    mobile: {},
    tablet: { '@media': `screen and (min-width: 768px)` },
    desktop: { '@media': `screen and (min-width: 1024px)` },
    hover: { selector: `&:hover` },
    focus: { selector: `&:focus` },
    active: { selector: `&:active` },
    visited: { selector: `&:visited` },
    disabled: { selector: `&:disabled` },
    checked: { selector: `&:checked` },
    first: { selector: `&:first-child` },
    last: { selector: `&:last-child` },
    odd: { selector: `&:nth-child(odd)` },
    even: { selector: `&:nth-child(even)` },
    empty: { selector: `&:empty` },
  },
  defaultCondition: `mobile`,
  properties: {
    display: [`none`, `block`, `flex`, `inline`, `inline-block`],
    flexDirection: [`row`, `column`],
    gap: vars.space,
    rowGap: vars.space,
    columnGap: vars.space,
    paddingTop: vars.space,
    paddingBottom: vars.space,
    paddingLeft: vars.space,
    paddingRight: vars.space,
    borderStyle: [`solid`, `dashed`, `dotted`, `none`],
    borderWidth: vars.space,
    borderColor: vars.color,
    margin: vars.space,
    width: vars.space,
    fontSize: vars.fontSize,
    fontWeight: vars.fontWeight,
    fontStyle: [`normal`, `italic`, `oblique`, `initial`, `inherit`],
    fontFamily: [
      `Recursive`,
      `GT-A`,
      `GT-A Mono`,
      `sans-serif`,
      `serif`,
      `monospace`,
    ],
    color: vars.color,
    // etc.
  },
  shorthands: {
    border: [`borderWidth`, `borderStyle`, `borderColor`],
    borderTop: [`borderWidth`, `borderStyle`, `borderColor`],
    borderRight: [`borderWidth`, `borderStyle`, `borderColor`],
    borderBottom: [`borderWidth`, `borderStyle`, `borderColor`],
    borderLeft: [`borderWidth`, `borderStyle`, `borderColor`],
    padding: [`paddingTop`, `paddingBottom`, `paddingLeft`, `paddingRight`],
    paddingX: [`paddingLeft`, `paddingRight`],
    paddingY: [`paddingTop`, `paddingBottom`],
  },
});

const colorStyles = defineProperties({
  properties: {
    // color: vars.color,
    background: vars.color,
    // backgroundColor: vars.color,
    // etc.
  },
});

export const atoms = createSprinkles(styles, colorStyles);
