export const colors = {
  red: [
    '#25140b',
    '#612a17',
    '#9f4122',
    '#d95930',
    '#ff7443',
    '#ff905d',
    '#ffac7c',
    '#ffc79f',
    '#ffe0c6',
    '#fff6ef',
  ],
  gold: [
    '#160f05',
    '#4a3411',
    '#835b15',
    '#b9811c',
    '#e8a32c',
    '#ffc046',
    '#ffd768',
    '#ffe68d',
    '#fff2b5',
    '#fffade',
  ],
  green: [
    '#071209',
    '#112d19',
    '#154a26',
    '#1d6736',
    '#308349',
    '#4c9e62',
    '#70b780',
    '#98cea2',
    '#c2e4c7',
    '#eef7ef',
  ],
  blue: [
    '#080d13',
    '#142132',
    '#1b3552',
    '#274a73',
    '#396191',
    '#557bad',
    '#7796c4',
    '#9cb3d8',
    '#c5d2e9',
    '#eef2f9',
  ],
  magenta: [
    '#120c14',
    '#2d1f33',
    '#4a3155',
    '#684476',
    '#845b95',
    '#a075b1',
    '#b991c8',
    '#cfb0db',
    '#e4d0eb',
    '#f8f2fa',
  ],
  grey: [
    '#0c0c0e',
    '#141416',
    '#1a1a1d',
    '#313033',
    '#616062',
    '#969596',
    '#cecdcc',
    '#f6f4f3',
    '#faf9f9',
    '#ffffff',
  ],
  // twitter: '#1da1f2',
  // facebook: '#3b5998',
  // instagram: '#e1306c',
}

const fonts = `system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', Helvetica, sans-serif`

const theme = {
  breakpoints: [32, 48, 64, 96, 128].map(w => `${w}em`),
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  fontSizes: [12, 16, 20, 24, 32, 48, 64, 96],
  config: {
    initialColorModeName: 'light',
    useColorSchemeMediaQuery: true,
  },
  colors: {
    ...colors,
    primary: colors.blue[5],
    accent: colors.red[4],
    inverted: colors.grey[9],
    text: colors.grey[0],
    background: colors.grey[9],
    elevated: colors.grey[8],
    sheet: colors.grey[8],
    sunken: colors.blue[9],
    border: colors.smoke,
    placeholder: colors.muted,
    secondary: colors.slate,
    muted: colors.grey[7],

    modes: {
      dark: {
        accent: colors.gold[6],
        inverted: colors.grey[0],
        text: colors.grey[9],
        background: colors.grey[0],
        elevated: colors.grey[1],
        sheet: colors.grey[1],
        sunken: colors.blue[1],
        border: colors.darkless,
        placeholder: colors.slate,
        secondary: colors.smoke,
        muted: colors.grey[2],
      },
    },
  },
  fonts: {
    monospace:
      '"Space Mono", ui-monospace, "Roboto Mono", Menlo, Consolas, monospace',
    heading: `"Inknut Antiqua", ui-rounded, ${fonts}`,
    body: `"Source Serif Pro", ${fonts}`,
  },
  lineHeights: { heading: 1.2, body: 1.4 },
  fontWeights: {
    body: 100,
    bold: 800,
    heading: 800,
  },
  letterSpacings: { tracked: '0.1em', negative: '-0.05em' },
  shadows: {
    text: '0 1px 2px rgba(0, 0, 0, 0.25), 0 2px 4px rgba(0, 0, 0, 0.125)',
    small: '0 1px 2px rgba(0, 0, 0, 0.0625), 0 2px 4px rgba(0, 0, 0, 0.0625)',
    card: '0 4px 8px rgba(0, 0, 0, 0.125)',
    elevated:
      '0 1px 2px rgba(0, 0, 0, 0.0625), 0 8px 12px rgba(0, 0, 0, 0.125)',
  },
  text: {
    heading: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      lineHeight: 'heading',
      letterSpacing: 'headline',
      mt: 0,
      mb: 0,
    },
    ultratitle: {
      fontSize: [5, 6, 7],
      lineHeight: 'title',
      fontWeight: 'heading',
      letterSpacing: 'title',
    },
    title: {
      variant: 'text.heading',
      fontSize: [5, 6],
      letterSpacing: 'title',
      lineHeight: 'title',
    },
    subtitle: {
      mt: 1,
      mb: 4,
      color: 'secondary',
      fontSize: [2, 3],
      fontFamily: 'body',
      fontWeight: 'body',
      letterSpacing: 'headline',
      lineHeight: 'subheading',
    },
    headline: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      letterSpacing: 'headline',
      lineHeight: 'heading',
      fontSize: 4,
      mt: 3,
      mb: 3,
    },
    subheadline: {
      fontFamily: 'heading',
      lineHeight: 'subheading',
      fontSize: 3,
      mt: 0,
      mb: 3,
    },
    eyebrow: {
      color: 'muted',
      fontSize: [3, 4],
      fontWeight: 'bold',
      letterSpacing: 'headline',
      lineHeight: 'subheading',
      textTransform: 'uppercase',
      mt: 0,
      mb: 2,
    },
    lead: {
      fontSize: [2, 3],
      my: [2, 3],
    },
    caption: {
      color: 'muted',
      fontSize: 1,
      letterSpacing: 'headline',
      lineHeight: 'caption',
    },
  },
  alerts: {
    primary: {
      borderRadius: 'default',
      bg: 'yellow',
      color: 'background',
      fontWeight: 'body',
      lineHeight: 'heading',
    },
  },
  badges: {
    pill: {
      borderRadius: 'circle',
      px: 3,
      py: 1,
    },
    outline: {
      borderRadius: 'circle',
      px: 3,
      py: 1,
      bg: 'transparent',
      borderStyle: 'solid',
      borderWidth: [3, 5],
      borderColor: 'currentColor',
    },
  },
  buttons: {
    primary: {
      py: 2,
      px: 3,
      textDecoration: 'none',
      display: 'inline-block',
      color: 'white',
      cursor: 'pointer',
      fontFamily: 'heading',
      fontWeight: 'bold',
      borderRadius: 'default',
      textShadow: 'none',
      boxShadow: 'card',
      WebkitTapHighlightColor: 'transparent',
      transition: 'transform .125s ease-in-out, box-shadow .125s ease-in-out',
      ':focus,:hover': {
        boxShadow: 'elevated',
        transform: 'scale(1.0625)',
      },
      svg: { ml: -1, mr: 2, verticalAlign: 'middle' },
    },
    lg: {
      variant: 'buttons.primary',
      fontSize: 3,
      lineHeight: 'title',
      px: 4,
      py: 3,
    },
    outline: {
      variant: 'buttons.primary',
      bg: 'transparent',
      color: 'primary',
      border: '3px solid currentColor',
    },
    outlineLg: {
      variant: 'buttons.primary',
      bg: 'transparent',
      color: 'primary',
      border: '2px solid currentColor',
      lineHeight: 'title',
      fontSize: 3,
      px: 4,
      py: 3,
    },
  },
  cards: {
    primary: {
      bg: 'elevated',
      color: 'text',
      p: [2, 3],
      borderRadius: '4px',
      boxShadow: 'card',
      overflow: 'hidden',
    },
  },
  forms: {
    input: {
      color: 'text',
      fontFamily: 'inherit',
      borderRadius: 'base',
      border: '1px solid',
      '::-webkit-input-placeholder': { color: 'placeholder' },
      '::-moz-placeholder': { color: 'placeholder' },
      ':-ms-input-placeholder': { color: 'placeholder' },
      '&[type="search"]::-webkit-search-decoration': { display: 'none' },
    },
    textarea: { variant: 'forms.input' },
    select: { variant: 'forms.input' },
    label: {
      color: 'text',
      display: 'flex',
      flexDirection: 'column',
      textAlign: 'left',
      lineHeight: 'caption',
      fontSize: 1,
    },
  },
  layout: {
    container: {
      maxWidth: ['layout', null, 'layoutPlus'],
      width: '100%',
      mx: 'auto',
      px: 4,
    },
    copy: {
      variant: 'layout.container',
      maxWidth: ['copy', null, 'copyPlus'],
    },
  },
  styles: {
    root: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
      fontSize: 1,
      color: 'text',
      bg: 'sheet',
      margin: 0,
      overflowX: 'hidden',
      minHeight: '100vh',
      textRendering: 'optimizeLegibility',
      WebkitFontSmoothing: 'antialiased',
      MozOsxFontSmoothing: 'grayscale',
      px: [3, 3, 4],
      py: 5,
      h1: {
        variant: 'text.heading',
        fontSize: [3, 4, 5],
      },
      h2: {
        variant: 'text.heading',
        fontSize: [2, 3, 4],
      },
      h3: {
        variant: 'text.heading',
        fontSize: [1, 2, 3],
        mb: 0,
      },
      h4: {
        variant: 'text.heading',
        fontSize: [0, 1, 2],
      },
      h5: {
        variant: 'text.heading',
        fontSize: 1,
      },
      h6: {
        variant: 'text.heading',
        fontSize: 0,
      },
      p: {
        color: 'text',
        fontWeight: 'body',
        lineHeight: 'body',
        my: 3,
      },
      small: { fontSize: 0 },
      img: {
        maxWidth: '100%',
      },
      hr: {
        border: '1px solid',
        borderColor: 'accent',
        mx: 'auto',
        my: 4,
      },
      a: {
        color: 'primary',
        textDecoration: 'inherit',
        fontWeight: 'bold',
        transition: 'color .125s ease-in-out',
        ':focus,:hover': {
          color: 'accent',
        },
      },
      pre: {
        fontFamily: 'monospace',
        fontSize: 1,
        p: 3,
        color: 'text',
        bg: 'sunken',
        overflow: 'auto',
        borderRadius: '4px',
        border: '1px solid',
      },
      code: {
        fontFamily: 'monospace',
        fontSize: 'inherit',
        color: 'text',
        bg: 'sunken',
        borderRadius: 'small',
        mx: 1,
        px: 1,
      },
      li: {
        my: 2,
      },
      table: {
        width: '100%',
        my: 4,
        borderCollapse: 'separate',
        borderSpacing: 0,
        'th,td': {
          textAlign: 'left',
          py: '4px',
          pr: '4px',
          pl: 0,
          borderColor: 'border',
          borderBottomStyle: 'solid',
        },
      },
      th: {
        verticalAlign: 'bottom',
        borderBottomWidth: '1px',
      },
      td: {
        verticalAlign: 'top',
        borderBottomWidth: '0.5px',
      },
    },
  },
  util: {
    motion: '@media (prefers-reduced-motion: no-preference)',
    reduceMotion: '@media (prefers-reduced-motion: reduce)',
    reduceTransparency: '@media (prefers-reduced-transparency: reduce)',
    supportsClipText: '@supports (-webkit-background-clip: text)',
    supportsBackdrop:
      '@supports (-webkit-backdrop-filter: none) or (backdrop-filter: none)',
  },
}

export default theme
